defaults: &defaults
 adapter: postgresql
 encoding: unicode
 username: postgres
 password: 
 host: localhost
 port: 5432

development:
 database: video_cloud_development
 <<: *defaults

test:
 database: video_cloud_test
 <<: *defaults
